image: node:latest

cache:
  paths:
    - elm-stuff

before_script:
  - export PATH=$PWD/node_modules/.bin:$PATH # we don't have perms to install with -g
  - npm install elm
  - npm install uglify-js
  - elm --version

elm-make:
  script:
    - make

elm-test:
  script:
    - npm install elm-test
    - elm-test --version
    - make test
